---
- name: Ensure dependency packages are installed
  package:
    name:
      - python3
      - python3-dev
      - py3-requests
      - py3-pip
      - py3-passlib
      - npm
      - git
      - curl
      - openssl
      - ca-certificates
      - dbus
      - bluez
      - openrc
      - avahi
      - avahi-tools
      - mdns-scan
      - tar
      - unzip
      - ufw
      - tzdata
    state: present

- name: Ensure Avahi (mDNS) service is enabled and started
  service:
    name: avahi-daemon
    state: started
    enabled: yes