data:
  configuration.yaml: |
    homeassistant: true
    permit_join: true
    mqtt:
      base_topic: zigbee2mqtt
      server: mqtt://mosquitto:1883
    serial:
      port: {{ zigbee_device_path }}
