---
- name: Create role directories
  file:
    path: "{{ dir.data }}/grafana"
    state: directory
    owner: "472"
    group: "472"
    mode: '0755'

- name: Run Grafana container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:latest
    restart: true
    restart_policy: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - name: "proxy"
    volumes:
      - "{{ dir.data }}/grafana:/var/lib/grafana"
    env:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    state: started
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.grafana.entrypoints: "web"
      traefik.http.routers.traefik.service: "grafana"
      traefik.http.routers.grafana.rule: "Host(`grafana.local`)"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"