---
- name: "Create directories for: {{ service.name }}"
  file:
    path: "{{ service.dir }}"
    state: directory
    owner: "472"
    group: "472"
    mode: '0755'

- name: Run Grafana container
  community.docker.docker_container:
    name: "{{ service.name }}"
    image: "{{ service.image }}:{{ service.version }}"
    restart: true
    restart_policy: unless-stopped
    ports:
      - "{{ service.port }}:3000"
    networks:
      - name: "proxy"
      - name: "{{ smarthome.network }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - "{{ service.dir }}:/var/lib/grafana"
    env:
      TZ: "{{ tz }}"
      PUID: "1000"
      PGID: "1000"
    state: started
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      "{{ 'traefik.http.routers.' ~ service.name ~ '.entrypoints' }}": "websecure"
      "{{ 'traefik.http.routers.' ~ service.name ~ '.service' }}": "{{ service.name }}"
      "{{ 'traefik.http.routers.' ~ service.name ~ '.rule' }}": "Host(`{{ service.name }}.local`)"
      "{{ 'traefik.http.routers.' ~ service.name ~ '.tls' }}": "true"
      "{{ 'traefik.http.routers.' ~ service.name ~ '.tls.certresolver' }}": "letsencrypt"
      "{{ 'traefik.http.services.' ~ service.name ~ '.loadbalancer.server.port' }}": "{{ service.port }}"