---
service:
  name: "{{ role_name }}"
  dir: "{{ dir.data }}/{{ role_name }}"
  logdir: "{{ dir.log }}/{{ role_name }}"
  image: ghcr.io/koenkk/zigbee2mqtt
  version: "{{ app[role_name].version }}"
  port: 8080
  domain: "{{ app[role_name].subdomain | default(role_name) }}.{{ smarthome.domain }}"
