---
- hosts: localhost
  vars_files:
    - ['settings.yml']
  roles:
    - role: common
    - role: docker
    - role: traefik
    - role: portainer
    - role: grafana
    - role: homeassistant
    - role: mosquitto
    # - role: zigbee2mqtt