---
app:
  homeassistant:
    version: latest
  mosquitto:
    version: latest
  zigbee2mqtt:
    version: latest
  esphome:
    version: latest
  node-red:
    version: latest
  grafana:
    version: latest
  traefik:
    version: latest
  portainer:
    version: latest

tz: Europe/Copenhagen
dir:
  data: "/opt"
  log: "/var/log"
user:
  name: emhome
  pass: smarthome
smarthome:
  network: proxy
  zigbee_adapter: "/dev/serial/by-id/usb-SMLIGHT_SMLIGHT_SLZB-07Mg24_fa8db40321adef11b54b924ba8793231-if00-port0"
  