---
TZ: "{{ tz }}"
dir:
  data: "/opt"
  log: "/var/log"
user:
  name: emhome
  pass: smarthome
smarthome:
  network: smarthome
  host_adapter: "/dev/serial/by-id/usb-SMLIGHT_SMLIGHT_SLZB-07Mg24_fa8db40321adef11b54b924ba8793231-if00-port0"
  guest_adapter: "/dev/ttyACM0"
  