---
app:
  homeassistant:
    version: latest
    subdomain: home
  mosquitto:
    version: latest
  zigbee2mqtt:
    version: latest
    subdomain: zigbee
  esphome:
    version: latest
  node-red:
    version: latest
  grafana:
    version: latest
  traefik:
    version: latest
  portainer:
    version: latest
  duckdns:
    version: latest

tz: Europe/Copenhagen
dir:
  data: "/opt"
  log: "/var/log"
user:
  name: emhome
  pass: smarthome
smarthome:
  # domain: local
  domain: duckdns.org
  network: proxy
  dns: ["8.8.4.4", "8.8.8.8"]
  zigbee_adapter: "/dev/serial/by-id/usb-SMLIGHT_SMLIGHT_SLZB-07Mg24_fa8db40321adef11b54b924ba8793231-if00-port0"
  