---
- hosts: localhost
  become: true
  become_method: doas
  become_user: root
  gather_facts: true

  tasks:
    - name: Read acme.json content
      slurp:
        src: "/opt/traefik/letsencrypt/acme.json"
      register: acme_json_content

    - name: Parse acme.json and check Certificates
      set_fact:
        acme_json_data: "{{ acme_json_content['content'] | b64decode | from_json }}"
        certificates_value: "{{ (acme_json_content['content'] | b64decode | from_json).letsencrypt.Certificates | default(None) }}"


    - name: DEBUG
      debug:
        var: acme_json_data

    - name: DEBUG 2
      debug:
        var: certificates_value

    # - name: Read /etc/os-release
    #   ansible.builtin.slurp:
    #     src: /etc/os-release
    #   register: system_os_file

    # - name: Set system_os fact from /etc/os-release
    #   set_fact:
    #     system_os: "{{ (system_os_file['content'] | b64decode).split('\n') | select('match', '^ID=') | list | first | regex_replace('^ID=\"?([^\"]+)\"?$', '\\1') }}"
    
    # - name: DEBUG
    #   debug:
    #     var: system_os

    # - name: Resolve real device path
    #   command: readlink -f /dev/serial/by-id/{{ usb_by_id_name }}
    #   register: device_real_path
