---
- hosts: localhost
  become: true
  become_method: doas
  become_user: root
  gather_facts: true

  tasks:
    - name: Wait for acme.json to have non-null Certificates and run nslookup on every retry
      shell: |
        set -e
        # Run nslookup for debugging
        docker exec -t traefik sh -c 'nslookup -type=TXT _acme-challenge.emwe.duckdns.org'
        # Check if acme.json exists and is not empty
        if [ ! -s "/opt/traefik/letsencrypt/acme.json" ]; then
          echo "acme.json does not exist or is empty"
          exit 1
        fi
      register: acme_check_result
      until: acme_check_result.rc == 0
      retries: 60
      delay: 5
      changed_when: false

    

    # - name: Read /etc/os-release
    #   ansible.builtin.slurp:
    #     src: /etc/os-release
    #   register: system_os_file

    # - name: Set system_os fact from /etc/os-release
    #   set_fact:
    #     system_os: "{{ (system_os_file['content'] | b64decode).split('\n') | select('match', '^ID=') | list | first | regex_replace('^ID=\"?([^\"]+)\"?$', '\\1') }}"
    
    # - name: DEBUG
    #   debug:
    #     var: system_os

    # - name: Resolve real device path
    #   command: readlink -f /dev/serial/by-id/{{ usb_by_id_name }}
    #   register: device_real_path
