---
- hosts: localhost
  become: true
  become_method: doas
  become_user: root
  gather_facts: true

  tasks:
    # - name: Read /etc/os-release
    #   ansible.builtin.slurp:
    #     src: /etc/os-release
    #   register: system_os_file

    # - name: Set system_os fact from /etc/os-release
    #   set_fact:
    #     system_os: "{{ (system_os_file['content'] | b64decode).split('\n') | select('match', '^ID=') | list | first | regex_replace('^ID=\"?([^\"]+)\"?$', '\\1') }}"
    
    # - name: DEBUG
    #   debug:
    #     var: system_os

    # - name: Resolve real device path
    #   command: readlink -f /dev/serial/by-id/{{ usb_by_id_name }}
    #   register: device_real_path
