---
- hosts: localhost
  become: true
  become_method: doas
  become_user: root
  gather_facts: true

  vars:
    usb_by_id_name: "usb-SMLIGHT_SMLIGHT_SLZB-07Mg24_fa8db40321adef11b54b924ba8793231-if00-port0"

  tasks:
    # - name: Read /etc/os-release
    #   ansible.builtin.slurp:
    #     src: /etc/os-release
    #   register: system_os_file

    # - name: Set system_os fact from /etc/os-release
    #   set_fact:
    #     system_os: "{{ (system_os_file['content'] | b64decode).split('\n') | select('match', '^ID=') | list | first | regex_replace('^ID=\"?([^\"]+)\"?$', '\\1') }}"
    
    # - name: DEBUG
    #   debug:
    #     var: system_os

    - name: Get the real device path from the by-id symlink
      command: readlink -f /dev/serial/by-id/{{ usb_by_id_name }}
      register: real_device_path
      changed_when: false


    - name: Get the serial number from the device's sysfs path
      shell: |
        udevadm info -q property -n {{ real_device_path.stdout }} | grep ID_SERIAL_SHORT= | cut -d= -f2
      register: device_serial
      changed_when: false

    - name: DEBUG
      debug:
        var: device_serial

    - name: Find all USB device directories with a serial file
      find:
        paths: /sys/bus/usb/devices/
        file_type: file
        patterns: serial
        follow: true
        limit: 1
        recurse: true
      register: usb_serial_files

    - name: DEBUG
      debug:
        var: usb_serial_files

    - name: Read serials from all USB device directories
      slurp:
        src: "{{ item.path }}"
      loop: "{{ usb_serial_files.files }}"
      register: usb_serial_contents

    - name: DEBUG
      debug:
        var: usb_serial_contents

    - name: Find the USB device directory matching the serial
      set_fact:
        matched_usb_device_dir: "{{ item.item.path | regex_replace('/serial$', '') }}"
      loop: "{{ usb_serial_contents.results }}"
      when: (item.content | b64decode | trim) == device_serial.stdout

    - name: Debug matched USB device directory
      debug:
        msg: "USB device directory for {{ usb_by_id_name }} is {{ matched_usb_device_dir }}"
      when: matched_usb_device_dir is defined