---
- name: Stop homeassistant
  docker_container:
    name: homeassistant
    state: stopped

- name: Start homeassistant
  docker_container:
    name: homeassistant
    state: started

- name: Restart homeassistant
  docker_container:
    name: homeassistant
    state: restarted

- name: Reload homeassistant
  docker_container:
    name: homeassistant
    state: reloaded