---
# - name: Enable Experimental mode for Bluetooth (enables battery monitoring of devices)
#   lineinfile:
#     dest: /etc/bluetooth/main.conf
#     regexp: '^#(Experimental = )(false|true)'
#     line: '\1true'
#     backrefs: yes
#     state: present

# DEBUG: create a task to restart bluetooth in case of errors?


- name: Get list of Bluetooth device names
  shell: |
    hciconfig | grep -o '^hci[0-9]\+'
  register: bluetooth_devices
  changed_when: false

- name: Ensure all Bluetooth devices are up
  shell: |
    hciconfig {{ item }} up
  loop: "{{ bluetooth_devices.stdout_lines }}"
  when: bluetooth_devices.stdout_lines | length > 0
  changed_when: false
  ignore_errors: yes

# - name: Comment out pipeline archive in fstab
#   replace:
#     dest: /etc/bluetooth/main.conf
#     regexp: '^#Experimental = false'
#     replace: 'Experimental = true'

