---
- name: Set Rebuild Fact
  set_fact:
    rebuild: true
  tags: ["rebuild", "never"]

- name: Prune Docker from containers and networks
  community.docker.docker_prune:
    containers: yes
    networks: yes
  tags: ["home", "never"]
  when: rebuild | default(false) | bool

# - name: Read /etc/os-release
#   ansible.builtin.slurp:
#     src: /etc/os-release
#   register: system_os_file

# - name: Set custom_os_name fact from /etc/os-release
#   set_fact:
#     system_os: "{{ (system_os_file['content'] | b64decode).split('\n') | select('match', '^ID=') | list | first | regex_replace('^ID=\"?([^\"]+)\"?$', '\\1') }}"