apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: smarthub-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/emwedk/emhome.git
  ref:
    branch: main
