---
- name: "Create directories for: {{ service.name }}"
  file:
    path: "{{ service.dir }}"
    state: "directory"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"

- name: "Run ESPHome container"
  community.docker.docker_container:
    name: "{{ service.name }}"
    image: "{{ service.image }}:{{ service.version }}"
    state: "started"
    restart: true
    restart_policy: "unless-stopped"
    networks:
      - name: "{{ smarthome.network }}"
    ports:
      - "{{ service.port }}:6052"
    volumes:
      - "{{ service.dir }}:/config"
    env:
      TZ: "{{ tz }}"
      PUID: "1000"
      PGID: "1000"
    labels:
      traefik.enable: "true"
      # traefik.docker.network: "{{ smarthome.network }}"
      traefik.http.routers.esphome.entrypoints: "web"
      traefik.http.routers.esphome.service: "{{ service.name }}"
      traefik.http.routers.esphome.rule: "Host(`{{ service.name }}.local`)"
      traefik.http.services.esphome.loadbalancer.server.port: "{{ service.port }}"