---
- name: Stop mosquitto
  docker_container:
    name: mosquitto
    state: stopped

- name: Start mosquitto
  docker_container:
    name: mosquitto
    state: started

- name: Restart mosquitto
  docker_container:
    name: mosquitto
    state: restarted

- name: Reload mosquitto
  docker_container:
    name: mosquitto
    state: reloaded