---
service:
  name: "{{ role_name }}"
  dir: "{{ dir.data }}/{{ role_name }}"
  logdir: "{{ dir.log }}/{{ role_name }}"
  image: lscr.io/linuxserver/changedetection.io
  version: "{{ app[role_name].version }}"
  port: 5000
  domain: "{{ app[role_name].subdomain | default(role_name) }}.{{ smarthome.domain }}"
