---
- name: "Stop {{ service.name }}"
  docker_container:
    name: "{{ service.name }}"
    state: stopped

- name: "Start {{ service.name }}"
  docker_container:
    name: "{{ service.name }}"
    state: started

- name: "Restart {{ service.name }}"
  docker_container:
    name: "{{ service.name }}"
    state: started
    restart: true