---
- name: "Create directories for: {{ service.name }}"
  file:
    path: "{{ service.dir }}"
    state: "directory"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"

- name: Deploy Zigbee2MQTT secret file
  template:
    src: secret.yaml.j2
    dest: "{{ service.dir }}/secret.yaml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
    force: no

- name: Deploy Zigbee2MQTT configuration file
  template:
    src: configuration.yaml.j2
    dest: "{{ service.dir }}/configuration.yaml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
    force: no



- name: "Run Zigbee2MQTT container"
  community.docker.docker_container:
    name: "{{ service.name }}"
    image: "{{ service.image }}:{{ service.version }}"
    state: "started"
    restart: true
    restart_policy: "unless-stopped"
    groups:
      - "dialout"
    networks:
      # - name: "proxy"
      - name: "proxy"
    ports:
      - "{{ service.port }}:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - "{{ service.dir }}:/app/data"
      - "{{ service.logdir }}:/app/data/log"
    devices:
      - "{{ smarthome.zigbee_adapter }}:{{ smarthome.zigbee_adapter }}"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ user.puid }}"
      PGID: "{{ user.pgid }}"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.zigbee2mqtt.entrypoints: "web"
      traefik.http.routers.zigbee2mqtt.service: "{{ service.name }}"
      traefik.http.routers.zigbee2mqtt.rule: "Host(`{{ service.name }}.local`)"
      traefik.http.services.zigbee2mqtt.loadbalancer.server.port: "{{ service.port }}"