- name: Install essential packages
  apk:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - git

- name: Install Docker
  apk:
    name:
      - docker
      - docker-cli
    state: present

- name: Enable and start Docker service
  service:
    name: docker
    enabled: true
    state: started
