- name: Install essential packages
  apk:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - git
    - tar
    - unzip
    - python3
    - py3-pip
    - py3-kubernetes

- name: Install Docker
  apk:
    name:
      - docker
      - docker-cli
    state: present

- name: Enable and start Docker service
  service:
    name: docker
    enabled: true
    state: started

- name: Install Python Kubernetes client
  pip:
    name: kubernetes
    executable: pip3