---
- name: Check for Zigbee USB device
  stat:
    path: "{{ smarthome.zigbee_adapter }}"
  register: adapter_check
  when:
    - smarthome.zigbee_adapter is defined
    - smarthome.zigbee_adapter | length > 0

- name: Include zigbee2mqtt role if Zigbee USB device is present and variable is set
  include_role:
    name: zigbee
  when:
    - adapter_check.stat.exists | default(false)