---
# - name: Allow current user to escalate with doas without password
#   copy:
#     dest: "/etc/doas.d/20-{{ user.name }}.conf"
#     content: "permit nopass {{ user.name }} as root\n"
#     owner: root
#     group: root
#     mode: '0755'

- name: Create common groups
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - dialout
    - bluetooth
    - tty
    - "{{ user.name }}"

- name: "Create user '{{ user.name }}'"
  user:
    name: "{{ user.name }}"
    # group: "{{ user.name }}"
    groups: "{{ user.name }},docker,dialout,tty,bluetooth"
    append: yes

- name: Reset SSH connection so the Docker user can run Docker commands
  meta: reset_connection

- name: "Ensure directory for container installations exists with proper permissions"
  file:
    path: "{{ dir.data }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'


# # FOR SXMO INTERFACE
# - name: Copy sxmo doas conf for user
#   copy:
#     src: /etc/doas.d/sxmo.conf
#     dest: "/etc/doas.d/{{ user.name }}.conf"
#     owner: "root"
#     group: "root"
#     mode: '0755'
#   tags: rebuild
#   when: system_os == "postmarketos"

# - name: Replace :wheel with {{ user.name }} in user's doas conf
#   replace:
#     path: "/etc/doas.d/{{ user.name }}.conf"
#     regexp: ":wheel"
#     replace: "{{ user.name }}"
#   tags: rebuild
#   when: system_os == "postmarketos"

# - name: Ensure doas.conf allows passwordless chown for Bluetooth devices
#   ansible.builtin.lineinfile:
#     path: /etc/doas.conf
#     line: "permit nopass {{ ansible_user_id }} as root cmd chown"
#     state: present
#     create: yes
#     validate: 'doas -C %s'

# - name: Ensure doas.conf allows passwordless chmod for Bluetooth devices
#   ansible.builtin.lineinfile:
#     path: /etc/doas.conf
#     line: "permit nopass {{ ansible_user_id }} as root cmd chmod"
#     state: present
#     create: yes
#     validate: 'doas -C %s'

