---
- name: Allow current user to escalate with doas without password
  copy:
    dest: "/etc/doas.d/20-{{ user.name }}.conf"
    content: "permit nopass {{ user.name }} as root\n"
    owner: root
    group: root
    mode: '0755'

- name: Create common groups
  group: "name={{ item }} state=present"
  with_items:
    - docker
    - dialout
    - bluetooth
    - "{{ user.name }}"

- name: "Create user '{{ user.name }}'"
  user:
    name: "{{ user.name }}"
    group: "{{ user.name }}"
    groups: "{{ user.name }},docker,dialout,bluetooth"
    append: yes

- name: "Ensure directory for container installations exists with proper permissions"
  file:
    path: "{{ dir.data }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
