---
- name: Stop portainer
  docker_container:
    name: portainer
    state: stopped

- name: Start portainer
  docker_container:
    name: portainer
    state: started

- name: Restart portainer
  docker_container:
    name: portainer
    state: started
    restart: true