apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: smarthub
spec:
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 12.2.2
  interval: 5m
