---
- name: "Create directories for: {{ service.name }}"
  file:
    path: "{{ service.dir }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'

- name: Run Portainer container
  community.docker.docker_container:
    name: "{{ service.name }}"
    image: "{{ service.image }}:{{ service.version }}"
    state: started
    restart: true
    restart_policy: unless-stopped
    networks:
      - name: "proxy"
      - name: "{{ smarthome.network }}"
    ports:
      - "8000:8000"
      - "{{ service.port }}:9000"
      - "9443:9443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ service.dir }}:/data"
    env:
      TZ: "{{ tz }}"
      # PUID: "1000"
      # PGID: "1000"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.portainer.entrypoints: "web"
      traefik.http.routers.portainer.service: "{{ service.name }}"
      traefik.http.routers.portainer.rule: "Host(`{{ service.name }}.local`)"
      traefik.http.services.portainer.loadbalancer.server.port: "{{ service.port }}"