---
- name: "Remove directories for: {{ service.name }}"
  file:
    path: "{{ item }}"
    state: "absent"
    force: true
  loop:
    - "{{ service.dir }}"
    - "{{ service.logdir }}"
  when: rebuild | default(false) | bool

- name: "Create directory for: {{ service.name }}"
  file:
    path: "{{ service.dir }}"
    state: "directory"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"

- name: Build dynamic labels dictionary
  set_fact:
    dynamic_labels: >-
      {{
        {
          'traefik.enable': 'true',
          'traefik.docker.network': smarthome.network,
          ('traefik.http.routers.' ~ service.name ~ '.rule'): 'Host(`' ~ service.domain ~ '`)',
          ('traefik.http.routers.' ~ service.name ~ '.entrypoints'): 'websecure',
          ('traefik.http.routers.' ~ service.name ~ '.service'): service.name,
          ('traefik.http.services.' ~ service.name ~ '.loadbalancer.server.port'): service.port,
          ('traefik.http.services.' ~ service.name ~ '.loadbalancer.passhostheader'): 'true',
          ('traefik.http.routers.' ~ service.name ~ '.middlewares'): 'comp',
          ('traefik.http.routers.' ~ service.name ~ '.middlewares'): 'sslheader'
        }
      }}

- name: "Run container: {{ service.name }}"
  community.docker.docker_container:
    name: "{{ service.name }}"
    image: "{{ service.image }}:{{ service.version }}"
    pull: yes
    recreate: "{{ rebuild }}"
    state: started
    restart: true
    restart_policy: unless-stopped
    networks:
      - name: "{{ smarthome.network }}"
        aliases:
          - "{{ service.name }}"
    ports:
      - "8000:8000"
      - "{{ service.port }}:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ service.dir }}:/data"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ user.puid }}"
      PGID: "{{ user.pgid }}"
    labels: "{{ dynamic_labels }}"
      # traefik.enable: "true"
      # traefik.docker.network: "{{ smarthome.network }}"
      # "traefik.http.routers.{{ service.name }}.entrypoints": "web"
      # "traefik.http.routers.{{ service.name }}.service": "{{ service.name }}"
      # "traefik.http.routers.{{ service.name }}.rule": "Host(`{{ service.name }}.local`)"
      # "traefik.http.services.{{ service.name }}.loadbalancer.server.port": "{{ service.port }}"