---
- name: "Create directory for: {{ service.name }}"
  file:
    path: "{{ service.dir }}"
    state: "directory"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"

- name: "Run container: {{ service.name }}"
  community.docker.docker_container:
    name: "{{ service.name }}"
    image: "{{ service.image }}:{{ service.version }}"
    state: started
    restart: true
    restart_policy: unless-stopped
    networks:
      - name: "{{ smarthome.network }}"
    ports:
      - "8000:8000"
      - "{{ service.port }}:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ service.dir }}:/data"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ user.puid }}"
      PGID: "{{ user.pgid }}"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "{{ smarthome.network }}"
      "traefik.http.routers.{{ service.name }}.entrypoints": "web"
      "traefik.http.routers.{{ service.name }}.service": "{{ service.name }}"
      "traefik.http.routers.{{ service.name }}.rule": "Host(`{{ service.name }}.local`)"
      "traefik.http.services.{{ service.name }}.loadbalancer.server.port": "{{ service.port }}"