---
- name: "Ensure network exists: {{ smarthome.network }}"
  when: smarthome.network != "host"
  community.docker.docker_network:
    name: "{{ smarthome.network }}"
    state: "present"
  register: docker_bridge_network

- name: "debug var"
  debug:
    var: docker_bridge_network

- name: "debug var"
  debug:
    var: docker_bridge_network

- name: "debug var"
  debug:
    var: docker_bridge_network

- name: Set Docker host gateway IP
  set_fact:
    docker_host_gateway: "{{ docker_bridge_network.gateway }}"

# - name: Allow traffic from Docker bridge subnet 172.20.0.0/16 via UFW
#   ansible.builtin.ufw:
#     rule: allow
#     from_ip: 172.20.0.0/16

# - name: Allow traffic from Docker bridge subnet 172.19.0.0/16 via UFW
#   ansible.builtin.ufw:
#     rule: allow
#     from_ip: 172.19.0.0/16

# - name: Allow traffic from Docker bridge subnet 172.18.0.0/16 via UFW
#   ansible.builtin.ufw:
#     rule: allow
#     from_ip: 172.18.0.0/16

# - name: Allow traffic from Docker bridge subnet 172.17.0.0/16 via UFW
#   ansible.builtin.ufw:
#     rule: allow
#     from_ip: 172.17.0.0/16

# - name: Allow traffic from Docker bridge subnet 172.16.0.0/16 via UFW
#   ansible.builtin.ufw:
#     rule: allow
#     from_ip: 172.16.0.0/16

