---
- name: "Ensure network exists: {{ smarthome.network }}"
  when: smarthome.network != "host"
  community.docker.docker_network:
    name: "{{ smarthome.network }}"
    state: "present"
  register: docker_bridge

- name: Extract docker host info
  set_fact:
    docker_host: "{{ docker_bridge.network.IPAM.Config | first }}"


- name: "Allow traffic from Docker bridge subnet {{ docker_host.Subnet }} via UFW"
  ansible.builtin.ufw:
    rule: allow
    from_ip: docker_host.Subnet

# - name: Allow traffic from Docker bridge subnet 172.19.0.0/16 via UFW
#   ansible.builtin.ufw:
#     rule: allow
#     from_ip: 172.19.0.0/16

# - name: Allow traffic from Docker bridge subnet 172.18.0.0/16 via UFW
#   ansible.builtin.ufw:
#     rule: allow
#     from_ip: 172.18.0.0/16

# - name: Allow traffic from Docker bridge subnet 172.17.0.0/16 via UFW
#   ansible.builtin.ufw:
#     rule: allow
#     from_ip: 172.17.0.0/16

# - name: Allow traffic from Docker bridge subnet 172.16.0.0/16 via UFW
#   ansible.builtin.ufw:
#     rule: allow
#     from_ip: 172.16.0.0/16

