---
- name: "Remove directories for: {{ service.name }}"
  file:
    path: "{{ item }}"
    state: "absent"
    force: true
  loop:
    - "{{ service.dir }}"
    - "{{ service.logdir }}"
  when: rebuild | default(false) | bool

- name: "Create directories for: {{ service.name }}"
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
  loop:
    - "{{ service.dir }}/config/http"
    - "{{ service.dir }}/data"
    - "{{ service.dir }}/http"
    - "{{ service.logdir }}"

- name: Deploy Mosquitto configuration file
  template:
    src: mosquitto.conf.j2
    dest: "{{ service.dir }}/config/mosquitto.conf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"
    force: no

- name: Deploy Mosquitto passwd file
  template:
    src: mosquitto.passwd.j2
    dest: "{{ service.dir }}/config/mosquitto.passwd"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"
    force: no

- name: Deploy Mosquitto passwd file
  template:
    src: mosquitto.passwd.j2
    dest: "{{ service.dir }}/config/mosquitto.acl"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"
    force: no

- name: Build dynamic labels dictionary
  set_fact:
    dynamic_labels: >-
      {{
        {
          'traefik.enable': 'true',
          'traefik.docker.network': smarthome.network,
          ('traefik.http.routers.' ~ service.name ~ '.rule'): 'Host(`' ~ service.domain ~ '`)',
          ('traefik.http.routers.' ~ service.name ~ '.entrypoints'): 'websecure',
          ('traefik.http.routers.' ~ service.name ~ '.service'): service.name,
        }
      }}
#('traefik.http.services.' ~ service.name ~ '.loadbalancer.server.port'): service.port,

- name: Wait until at least one file exists in /opt/certs
  shell: 'ls -1 {{ dir.certs }} | grep .'
  register: certs_present
  retries: 60
  delay: 5
  until: certs_present.stdout != ""

- name: "Run container: {{ service.name }}"
  community.docker.docker_container:
    name: "{{ service.name }}"
    hostname: "{{ service.name }}"
    domainname : "{{ smarthome.domain }}"
    image: "{{ service.image }}:{{ service.version }}"
    pull: "{{ update }}"
    recreate: "{{ rebuild }}"
    state: started
    restart: true
    restart_policy: unless-stopped
    networks:
      - name: "{{ smarthome.network }}"
        aliases:
          - "{{ service.name }}"
    ports:
      - "127.0.0.1:1883:1883"
      - "127.0.0.1:1884:1884"
      - "127.0.0.1:8883:8883"
      - "127.0.0.1:8884:8884"
      - "127.0.0.1:8885:8885"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8090:8090"
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:8091:8091"
      - "127.0.0.1:8888:8888"
    volumes:
      - "{{ service.dir }}/config:/mosquitto/config"
      - "{{ service.dir }}/data:/mosquitto/data"
      - "{{ service.logdir }}:/mosquitto/log"
      - "{{ dir.certs }}:/mosquitto/certs"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ user.puid }}"
      PGID: "{{ user.pgid }}"
    labels: "{{ dynamic_labels }}"

- name: Wait for Mosquitto container to be running
  community.docker.docker_container_info:
    name: "{{ service.name }}"
  register: mosquitto_info
  until: mosquitto_info.container.State.Status == "running"
  retries: 10
  delay: 3

- name: Creating Mosquitto account and password
  community.docker.docker_container_exec:
    container: "{{ service.name }}"
    command: "mosquitto_passwd -b -c /mosquitto/config/mosquitto.passwd {{ user.name }} {{ user.pass }}"
  until: mosquitto_info.container.State.Status == "running"
  retries: 10
  delay: 3
  notify: Restart mosquitto

- name: Install Zigbee2MQTT if adapter is present
  import_tasks: "subtasks/mqtt_check.yml"
