---
- name: Create role directories
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
  loop:
    - "{{ mosquitto.dir }}/config"
    - "{{ mosquitto.dir }}/data"
    - "{{ dir.log }}/mosquitto/"

- name: "Ensure network exists ({{ mosquitto.network }})"
  when: mosquitto.network != "host"
  community.docker.docker_network:
    name: "{{ mosquitto.network }}"
    state: "present"

- name: Deploy Mosquitto configuration file
  template:
    src: mosquitto.conf.j2
    dest: "{{ mosquitto.dir }}/config/mosquitto.conf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"

- name: Deploy Mosquitto passwd file
  template:
    src: mosquitto.passwd.j2
    dest: "{{ mosquitto.dir }}/config/mosquitto.passwd"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"

- name: Run Mosquitto container
  community.docker.docker_container:
    name: mosquitto
    image: eclipse-mosquitto:latest
    restart: true
    restart_policy: unless-stopped
    ports:
      - "{{ mosquitto.port }}:1883"
      - "9001:9001"
    volumes:
      - "{{ mosquitto.dir }}/config:/mosquitto/config"
      - "{{ mosquitto.dir }}/data:/mosquitto/data"
      - "{{ dir.log }}/mosquitto:/mosquitto/log"
    env:
      TZ: "{{ tz }}"
    state: started

- name: Wait for Mosquitto container to be running
  community.docker.docker_container_info:
    name: mosquitto
  register: mosquitto_info
  until: mosquitto_info.container.State.Status == "running"
  retries: 10
  delay: 3

- name: Creating Mosquitto account and password
  community.docker.docker_container_exec:
    container: mosquitto
    command: "mosquitto_passwd -b -c /mosquitto/config/mosquitto.passwd {{ user.name }} {{ user.pass }}"

- name: Install Zigbee2MQTT if adapter is present
  import_tasks: "subtasks/mqtt_check.yml"