---
- name: Allow current user to escalate with doas without password
  become: true
  become_method: doas
  become_user: root
  ansible.builtin.copy:
    dest: "/etc/doas.d/20-{{ user.name }}.conf"
    content: "permit nopass {{ user.name }} as root\n"
    owner: root
    group: root
    mode: '0755'

- name: Ensure dependency packages are installed
  become: true
  become_method: doas
  package:
    name:
      - python3
      - python3-dev
      - py3-pip
      - npm
      - git
      - curl
      - dbus
      - bluez
      - openrc
      - tar
      - unzip
    state: present

- name: Create common groups
  become: true
  become_method: doas
  group: "name={{ item }} state=present"
  with_items:
    - docker
    - "{{ user.name }}"

- name: "Create user '{{ user.name }}'"
  become: true
  become_method: doas
  user:
    name: "{{ user.name }}"
    group: "{{ user.name }}"
    groups: "{{ user.name }},sudo,doas,docker,dialout,bluetooth"
    append: yes

- name: "Ensure directory for container installations exists with proper permissions"
  become: true
  become_method: doas
  file:
    path: "{{ dir.data }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'

- name: Check for Bluetooth device (optional)
  become: true
  become_method: doas
  shell: "hciconfig | grep -q hci0"
  register: bt_check
  ignore_errors: true

- name: Warn if Bluetooth device not found
  debug:
    msg: "Bluetooth device not found. Bluetooth features will be unavailable."
  when: bt_check.rc != 0