---
- name: Ensure dependency packages are installed
  package:
    name:
      - python3
      - python3-dev
      - python3-venv
      - py3-pip
      - npm
      - git
      - curl
      - dbus
      - bluez
      - openrc
      - tar
      - unzip
    state: present

- name: Ensure user is in docker, dialout, and bluetooth groups
  user:
    name: "{{ user.name }}"
    groups: docker,dialout,bluetooth
    append: yes

- name: "Ensure directory for container installations exists with proper permissions"
  file:
    path: "{{ dir.data }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'

- name: Check for Zigbee USB device
  stat:
    path: "{{ smarthome.host_adapter }}"
  register: adapter_check
  when:
    - smarthome.host_adapter is defined
    - smarthome.host_adapter | length > 0

- name: Include zigbee2mqtt role if Zigbee USB device is present and variable is set
  include_role:
    name: zigbee2mqtt
  when:
    - adapter_check.stat.exists | default(false)

- name: Check for Bluetooth device (optional)
  shell: "hciconfig | grep -q hci0"
  register: bt_check
  ignore_errors: true

- name: Warn if Bluetooth device not found
  debug:
    msg: "Bluetooth device not found. Bluetooth features will be unavailable."
  when: bt_check.rc != 0