---
service:
  name: "{{ role_name }}"
  dir: "{{ dir.data }}/{{ role_name }}"
  logdir: "{{ dir.log }}/{{ role_name }}"
  image: ghcr.io/esphome/esphome
  version: "{{ app[role_name].version }}"
  port: 6052
  domain: "{{ app[role_name].subdomain | default(role_name) }}.{{ smarthome.domain }}"
