---
- name: Stop grafana
  docker_container:
    name: grafana
    state: stopped

- name: Start grafana
  docker_container:
    name: grafana
    state: started

- name: Restart grafana
  docker_container:
    name: grafana
    state: started
    restart: true