---
- name: Stop traefik
  docker_container:
    name: traefik
    state: stopped

- name: Start traefik
  docker_container:
    name: traefik
    state: started

- name: Restart traefik
  docker_container:
    name: traefik
    state: started
    restart: true