- name: "Create directories for: {{ service.name }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
  loop:
    - "{{ service.dir }}"
    - "{{ service.dir }}/letsencrypt"

- name: Copy Traefik config
  template:
    src: traefik.yml.j2
    dest: "{{ service.dir }}/traefik.yml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0644'
    force: no

- name: Copy Traefik dynamic config
  template:
    src: traefik_dynamic.yml.j2
    dest: "{{ service.dir }}/traefik_dynamic.yml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0644'
    force: no

- name: Create Let's Encrypt resolver file
  copy:
    dest: "{{ service.dir }}/letsencrypt/acme.json"
    content: ""
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0600"
    force: no

- name: "Ensure network exists (proxy)"
  community.docker.docker_network:
    name: "proxy"
    state: "present"

- name: Run Traefik container
  become: true
  community.docker.docker_container:
    name: "{{ service.name }}"
    image: "{{ service.image }}:{{ service.version }}"
    state: started
    restart: true
    restart_policy: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # - "--providers.docker.network=proxy"
      # - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      # - "--providers.file.filename=/etc/traefik/traefik_dynamic.yml"
      # - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.email={{ letsencrypt.email }}"
      - "--certificatesresolvers.le.acme.storage=/etc/traefik/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      # - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--accesslog=true"
      - "--log.level=INFO"
    networks:
      # - name: proxy
      - name: "{{ smarthome.network }}"
    ports:
      - "80:80"
      - "{{ service.port }}:8080"
      - "443:443"
    etc_hosts:
      host.docker.internal: host-gateway
    dns_servers:
      - 8.8.8.8
      - 1.1.1.1
    labels:
        # APP: "{{ service.name }}"
        traefik.enable: "true"
        # traefik.docker.network: "proxy"
        traefik.http.routers.api.rule: "Host(`{{ service.name }}.local`)"
        traefik.http.routers.api.service: "api@internal"
        traefik.http.routers.api.entrypoints: "web"
        # traefik.http.routers.api.entrypoints: "websecure"
        # traefik.http.routers.api.tls.certresolver: "le"
        # traefik.http.routers.traefik.middlewares: "user-auth@file"

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # - /etc/resolv.conf:/etc/resolv.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - "{{ service.dir }}/traefik.yml:/etc/traefik/traefik.yml"
      # - "{{ service.dir }}/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml"
      - "{{ service.dir }}/letsencrypt:/etc/traefik/letsencrypt"
    env:
      TZ: "{{ tz }}"
      PUID: "1000"
      PGID: "1000"