- name: "Create directory for: {{ service.name }}"
  file:
    path: "{{ service.dir }}/letsencrypt"
    state: "directory"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"

# - name: Copy Traefik config
#   template:
#     src: traefik.yml.j2
#     dest: "{{ service.dir }}/traefik.yml"
#     owner: "{{ user.name }}"
#     group: "{{ user.name }}"
#     mode: '0644'

- name: Copy Traefik dynamic config
  template:
    src: traefik_dynamic.yml.j2
    dest: "{{ service.dir }}/traefik_dynamic.yml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0644'

- name: Set acme.json permissions
  copy:
    dest: "{{ service.dir }}/letsencrypt/acme.json"
    content: ""
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0600"
    force: no

- name: "Run container: {{ service.name }}"
  # become: true
  community.docker.docker_container:
    name: "{{ service.name }}"
    image: "{{ service.image }}:{{ service.version }}"
    state: started
    restart: true
    restart_policy: unless-stopped
    networks:
      - name: "{{ smarthome.network }}"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    etc_hosts:
      host.docker.internal: host-gateway
      # host.docker.internal: 172.17.0.1

    volumes:
      - /etc/resolv.conf:/etc/resolv.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - "{{ service.dir }}/traefik.yml:/etc/traefik/traefik.yml"
      - "{{ service.dir }}/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml"
      # - "{{ service.dir }}/letsencrypt:/etc/traefik/letsencrypt"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ user.puid }}"
      PGID: "{{ user.pgid }}"
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network={{ smarthome.network }}"
      # - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.file.filename=/etc/traefik/traefik_dynamic.yml"
      - "--providers.file.watch=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--metrics.prometheus=true"

    labels:
      - "--traefik.enable=true"
      - "--traefik.docker.network={{ smarthome.network }}"
      - "--traefik.http.routers.{{ service.name }}.entrypoints=web"
      - "--traefik.http.routers.{{ service.name }}.service=api@internal"
      - "--traefik.http.routers.{{ service.name }}.rule=Host(`{{ service.name }}.local`)"

      - "--traefik.http.middlewares.{{ service.name }}-auth.basicauth.users={{ user.name }}:{{ user.pass | password_hash('sha512') }}"
      - "--traefik.http.routers.{{ service.name }}.middlewares={{ service.name }}-auth@docker"

      # - "traefik.http.services.{{ service.name }}.loadbalancer.server.port={{ service.port }}"

        # APP: "traefik"
        # traefik.enable: "true"
        # traefik.docker.network: "{{ smarthome.network }}"
        # traefik.http.routers.traefik.entrypoints: "web"
        # traefik.http.routers.traefik.rule: "Host(`traefik.local`)"
        # traefik.http.routers.traefik.middlewares: "user-auth@file"
        # traefik.http.routers.traefik.service: "api@internal"

    