- name: "Create role directories"
  file:
    path: "{{ dir.data }}/traefik"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'

- name: Copy Traefik dynamic config
  template:
    src: dynamic.yml.j2
    dest: "{{ dir.data }}/traefik/dynamic.yml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0644'

- name: "Create acme directory"
  file:
    path: "{{ dir.data }}/traefik/acme"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'

- name: Set acme.json permissions
  copy:
    dest: "{{ dir.data }}/traefik/acme/acme.json"
    content: ""
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0600"
    force: no

- name: Run Traefik container
  community.docker.docker_container:
    name: traefik
    image: traefik:latest
    state: started
    restart: true
    restart_policy: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    # etc_hosts:
    #   host.docker.internal: 172.17.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ dir.data }}/traefik:/etc/traefik"
    env:
      TZ: "{{ tz }}"