- name: "Create directory for: {{ service.name }}"
  file:
    path: "{{ service.dir }}/letsencrypt"
    state: "directory"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"

# - name: Copy Traefik config
#   template:
#     src: traefik.yml.j2
#     dest: "{{ service.dir }}/traefik.yml"
#     owner: "{{ user.name }}"
#     group: "{{ user.name }}"
#     mode: '0644'

- name: Copy Traefik dynamic config
  template:
    src: traefik_dynamic.yml.j2
    dest: "{{ service.dir }}/traefik_dynamic.yml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0644'

- name: Set acme.json permissions
  copy:
    dest: "{{ service.dir }}/letsencrypt/acme.json"
    content: ""
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0600"
    force: no



- name: Build dynamic labels dictionary
  set_fact:
    dynamic_labels: >-
      {{
        {
          'traefik.enable': 'true',
          'traefik.docker.network': smarthome.network,
          ('traefik.http.routers.' ~ service.name ~ '-dashboard.rule'): 'Host(`' ~ (app[service.name].subdomain | default(service.name)) ~ '.' ~ smarthome.domain ~ '`) && PathPrefix(`/dashboard`) || PathPrefix(`/api`)',
          ('traefik.http.routers.' ~ service.name ~ '-dashboard.entrypoints'): 'websecure',
          ('traefik.http.routers.' ~ service.name ~ '-dashboard.service'): 'api@internal',
          ('traefik.http.routers.' ~ service.name ~ '-dashboard.middlewares'): service.name ~ '-auth',
          ('traefik.http.services.' ~ service.name ~ '-dashboard.loadbalancer.server.port'): service.port,
          ('traefik.http.middlewares.' ~ service.name ~ '-auth.basicauth.users'): user.name ~ ':' ~ (user.pass | password_hash('md5')),
          
          
        }
      }}
#('traefik.http.services.' ~ service.name ~ '.loadbalancer.server.port'): service.port
#('traefik.http.routers.' ~ service.name ~ '.rule'): 'Host(`' ~ service.name ~ '.local`)',
#('traefik.http.middlewares.' ~ service.name ~ '-auth.basicauth.users'): user.name ~ ':' ~ (user.pass | password_hash('sha512')),
#('traefik.http.routers.' ~ service.name ~ '-secure.tls.domains[0].main'): smarthome.domain,
#('traefik.http.routers.' ~ service.name ~ '-secure.tls.domains[0].sans'): '*.' ~ smarthome.domain,
#('traefik.http.routers.http-catchall.middlewares'): 'redirect-to-https',
#('traefik.http.middlewares.redirect-to-https.redirectscheme.scheme'): 'https',
#('traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto'): 'https'
#('traefik.http.services.' ~ service.name ~ '-dashboard.loadbalancer.passhostheader'): 'true',
#('traefik.http.routers.http-catchall.rule'): 'HostRegexp(`{host:.+}`)',
#('traefik.http.routers.' ~ service.name ~ '-dashboard.tls'): 'true',
#('traefik.http.routers.' ~ service.name ~ '-dashboard.tls.certresolver'): 'letsencrypt',



- name: "Run container: {{ service.name }}"
  community.docker.docker_container:
    name: "{{ service.name }}"
    image: "{{ service.image }}:{{ service.version }}"
    state: started
    restart: true
    restart_policy: unless-stopped
    security_opts:
      - no-new-privileges=true
    # dns_servers:
    #   - 1.1.1.1
    #   - 8.8.8.8
    # dns_search_domains: []
    networks:
      - name: bridge
      - name: "{{ smarthome.network }}"
    ports:
      - "80:80"
      - "443:443"
    etc_hosts:
      # host.docker.internal: host-gateway
      # host.docker.internal: 172.18.0.1
      host.docker.internal: "{{ docker_host.Gateway }}"

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "/etc/hosts:/etc/hosts"
      # - /etc/resolv.conf:/etc/resolv.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - "{{ service.dir }}/traefik.yml:/etc/traefik/traefik.yml"
      - "{{ service.dir }}/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml"
      - "{{ service.dir }}/letsencrypt:/etc/traefik/letsencrypt"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ user.puid }}"
      PGID: "{{ user.pgid }}"
      TRAEFIK_DASHBOARD_CREDENTIALS: "{{ user.name }}:{{ user.pass | password_hash('md5') }}"
      DUCKDNS_TOKEN: "{{ secret.duckdns.token }}"
      DUCKDNS_DOMAIN: "{{ secret.duckdns.domain }}"
      DUCKDNS_PROPAGATION_TIMEOUT: "1800"
      DUCKDNS_SUBDOMAIN: "{{ secret.duckdns.domain }}"
      # DNS: "1.1.1.1,8.8.8.8"
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.asDefault=true"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main={{ smarthome.domain }}"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.{{ smarthome.domain }}"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=duckdns"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.propagation.delayBeforeChecks=1800"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.propagation.disableChecks=true"
      - "--certificatesresolvers.letsencrypt.acme.email={{ secret.letsencrypt.email }}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      # - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" # letsencrypt staging server
      # - "--certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      # - "--providers.docker.network={{ smarthome.network }}"
      # - "--providers.docker.watch=true"
      - "--providers.file.filename=/etc/traefik/traefik_dynamic.yml"
      - "--providers.file.watch=true"


    labels: "{{ dynamic_labels }}"
        

      

        