- name: "Create directory for: {{ service.name }}"
  file:
    path: "{{ service.dir }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'

- name: Deploy Home Assistant configuration file
  template:
    src: configuration.yaml.j2
    dest: "{{ service.dir }}/configuration.yaml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
    force: no

- name: Deploy Home Assistant secret file
  template:
    src: secret.yaml.j2
    dest: "{{ service.dir }}/secret.yaml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"

- name: Ensure Home Assistant include folders exist
  file:
    path: "{{ service.dir }}/{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
  loop:
    - automations
    - themes

- name: Ensure Home Assistant include files exist
  copy:
    dest: "{{ service.dir }}/{{ item }}"
    content: ""
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
    force: no
  loop:
    - automations.yaml
    - customize.yaml
    - groups.yaml
    - scripts.yaml
    - scenes.yaml
    - template.yaml

- name: Build dynamic labels dictionary
  set_fact:
    dynamic_labels: >-
      {{
        {
          'traefik.enable': 'true',
          'traefik.docker.network': smarthome.network,
          ('traefik.http.routers.' ~ service.name ~ '.rule'): 'Host(`' ~ smarthome.domain ~ '`)',
          ('traefik.http.routers.' ~ service.name ~ '.service'): service.name,
          ('traefik.http.routers.' ~ service.name ~ '.entrypoints'): 'websecure',
          ('traefik.http.services.' ~ service.name ~ '.loadbalancer.server.port'): service.port,
          ('traefik.http.routers.' ~ service.name ~ '.tls'): 'true',
          ('traefik.http.routers.' ~ service.name ~ '.tls.certresolver'): 'letsencrypt',
          ('traefik.http.services.' ~ service.name ~ '.loadbalancer.passhostheader'): 'true',
          ('traefik.http.routers.' ~ service.name ~ '-.middlewares'): 'compresstraefik',
          ('traefik.http.middlewares.compresstraefik.compress'): 'true',
        }
      }}
  
  #('traefik.http.routers.' ~ service.name ~ '.rule'): 'Host(`' ~ (app[service.name].subdomain | default(service.name)) ~ '.local`) || Host(`' ~ (app[service.name].subdomain | default(service.name)) ~ '.' ~ secret.duckdns.domain ~ '.duckdns.org`) && PathPrefix(`/`) || Host(`' ~ ansible_default_ipv4.address ~ '`) && PathPrefix(`/`)',
  #'traefik.docker.network': smarthome.network,
  #('traefik.http.services.' ~ service.name ~ '.loadbalancer.server.port'): service.port

  #('traefik.http.routers.' ~ service.name ~ '.middlewares'): 'compresstraefik',
  #('traefik.http.middlewares.' ~ service.name ~ '.compress'): true,

- name: "Run container: {{ service.name }}"
  community.docker.docker_container:
    name: "{{ service.name }}"
    image: "{{ service.image }}:{{ service.version }}"
    state: started
    restart: true
    restart_policy: unless-stopped
    # privileged: true # only needed for official image
    network_mode: host
    # etc_hosts:
    #   # host.docker.internal: host-gateway
    #   # host.docker.internal: 172.18.0.1
    #   host.docker.internal: "{{ docker_host.Gateway }}"
    # dns_servers:
    #   - 1.1.1.1
    #   - 8.8.8.8
    # networks:
    #   - name: "{{ smarthome.network }}"
    volumes:
      - /var/run/dbus:/var/run/dbus:ro
      # - /etc/resolv.conf:/etc/resolv.conf
      - /etc/localtime:/etc/localtime:ro
      - "{{ service.dir }}:/config"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ user.puid }}"
      PGID: "{{ user.pgid }}"
      DOCKER_MODS: "linuxserver/mods:homeassistant-hacs"
    capabilities:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
      - SYS_ADMIN
    devices:
      - "{{ smarthome.zigbee_adapter }}"
      - "/dev/ttyS0:/dev/ttyS0"
    labels: "{{ dynamic_labels }}"
      # traefik.enable: "true"
      # traefik.docker.network: "{{ smarthome.network }}"
      # traefik.http.routers.{{ service.name }}.entrypoints: "web"
      # traefik.http.routers.{{ service.name }}.service: "{{ service.name }}"
      # traefik.http.routers.{{ service.name }}.rule: "Host(`{{ ansible_default_ipv4.address }}`) && PathPrefix(`/`)"
      # traefik.http.services.{{ service.name }}.loadbalancer.server.port: "{{ service.port }}"

      # traefik.enable: "true"
      # traefik.docker.network: "{{ smarthome.network }}"
      # traefik.http.routers.homeassistant.entrypoints: "web"
      # traefik.http.routers.homeassistant.service: "homeassistant"
      # traefik.http.routers.homeassistant.rule: "Host(`192.168.0.180`) && PathPrefix(`/`)"
      # traefik.http.services.homeassistant.loadbalancer.server.port: "{{ homeassistant.port }}"
