- name: "Create directories for: {{ service.name }}"
  file:
    path: "{{ service.dir }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'

- name: Deploy Home Assistant configuration file
  template:
    src: configuration.yaml.j2
    dest: "{{ service.dir }}/configuration.yaml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
    force: no

- name: Ensure Home Assistant include folders exist
  file:
    path: "{{ service.dir }}/{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
  loop:
    - automations
    - themes

- name: Ensure Home Assistant include files exist
  copy:
    dest: "{{ service.dir }}/{{ item }}"
    content: ""
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
    force: no
  loop:
    - automations.yaml
    - customize.yaml
    - groups.yaml
    - scripts.yaml
    - scenes.yaml
    - template.yaml

- name: Run Home Assistant container
  community.docker.docker_container:
    name: "{{ service.name }}"
    image: "{{ service.image }}:{{ service.version }}"
    state: started
    restart: true
    restart_policy: unless-stopped
    privileged: true
    network_mode: host
    # dns_servers:
    #   - 8.8.8.8
    #   - 1.1.1.1
    # networks:
    #   - name: "proxy"
    #   - name: "{{ smarthome.network }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # - /etc/resolv.conf:/etc/resolv.conf
      - /run/dbus:/run/dbus:ro
      - "{{ service.dir }}:/config"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ user.puid }}"
      PGID: "{{ user.pgid }}"
      # PUID: "1000"
      # PGID: "1000"
    capabilities:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - SYS_ADMIN
    devices:
      - "{{ smarthome.zigbee_adapter }}:{{ smarthome.zigbee_adapter }}"
      # Uncomment and adjust if Bluetooth device is present
      # - "/dev/ttyS0:/dev/ttyS0"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      # traefik.http.routers.homeassistant.service: "{{ service.name }}"
      # traefik.http.routers.homeassistant-local.rule: "Host(`192.168.0.180`) && PathPrefix(`/`)"

      traefik.http.routers.ha-router.rule: "Host(`{{ ansible_default_ipv4.address }}`) && PathPrefix(`/`)"
      traefik.http.routers.ha-router.entrypoints: "websecure"
      traefik.http.routers.ha-router.service: "ha-service"
      traefik.http.routers.ha-router.tls: "true"
      traefik.http.routers.ha-router.middlewares: "default-headers,https-redirect"

      # Service
      traefik.http.services.ha-service.loadbalancer.server.port: "8123"

      # Middleware: https redirect
      traefik.http.middlewares.https-redirect.redirectscheme.scheme: "https"
      traefik.http.middlewares.https-redirect.redirectscheme.permanent: "true"

      # Middleware: default security headers
      traefik.http.middlewares.default-headers.headers.framedeny: "true"
      traefik.http.middlewares.default-headers.headers.sslredirect: "true"
      traefik.http.middlewares.default-headers.headers.browserxssfilter: "true"
      traefik.http.middlewares.default-headers.headers.contenttypenosniff: "true"
      traefik.http.middlewares.default-headers.headers.forcestsheader: "true"
      traefik.http.middlewares.default-headers.headers.stsincludesubdomains: "true"
      traefik.http.middlewares.default-headers.headers.stspreload: "true"
      traefik.http.middlewares.default-headers.headers.stsseconds: "15552000"
      traefik.http.middlewares.default-headers.headers.customframeoptionsvalue: "SAMEORIGIN"
      traefik.http.middlewares.default-headers.headers.customrequestheaders.X-Forwarded-Proto: "https"

      # Middleware: default whitelist
      traefik.http.middlewares.default-whitelist.ipwhitelist.sourcerange: "10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"

      # Middleware: secured chain
      traefik.http.middlewares.secured.chain.middlewares: "default-headers"

      # traefik.http.routers.homeassistant.entrypoints: "web"
      # traefik.http.routers.homeassistant.service: "homeassistant"
      # traefik.http.routers.homeassistant.rule: "Host(`{{ ansible_default_ipv4.address }}`) && PathPrefix(`/`)"

      # traefik.http.routers.homeassistant-le.entrypoints: "websecure"
      # traefik.http.routers.homeassistant-le.service: "homeassistant"
      # traefik.http.routers.homeassistant-le.tls.certresolver: "le"
      # traefik.http.routers.homeassistant-le.rule: "Host(`emwe.duckdns.org`)"

      traefik.http.services.homeassistant.loadbalancer.server.port: "{{ service.port }}"