- name: Create role directories
  file:
    path: "{{ homeassistant.dir }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'

- name: "Ensure network exists ({{ homeassistant.network }})"
  when: homeassistant.network != "host"
  community.docker.docker_network:
    name: "{{ homeassistant.network }}"
    state: "present"

- name: Deploy Home Assistant configuration file
  template:
    src: configuration.yaml.j2
    dest: "{{ homeassistant.dir }}/configuration.yaml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"

- name: Run Home Assistant container
  community.docker.docker_container:
    name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: true
    restart_policy: unless-stopped
    privileged: true
    network_mode: host
    expose:
      - 8123
    ports:
      - "8123:8123"
    volumes:
      - "{{ homeassistant.dir }}:/config"
      - /run/dbus:/run/dbus:ro
    env:
      TZ: "{{ tz }}"
    devices:
      - "{{ smarthome.host_adapter }}:{{ smarthome.host_adapter }}"
      # Uncomment and adjust if Bluetooth device is present
      # - "/dev/ttyS0:/dev/ttyS0"
    state: started