- name: "Create directories for: {{ service.name }}"
  file:
    path: "{{ service.dir }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'

- name: Deploy Home Assistant configuration file
  template:
    src: configuration.yaml.j2
    dest: "{{ service.dir }}/configuration.yaml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
    force: no

- name: Ensure Home Assistant include folders exist
  file:
    path: "{{ service.dir }}/{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
  loop:
    - automations
    - themes

- name: Ensure Home Assistant include files exist
  copy:
    dest: "{{ service.dir }}/{{ item }}"
    content: ""
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
    force: no
  loop:
    - automations.yaml
    - customize.yaml
    - groups.yaml
    - scripts.yaml
    - scenes.yaml
    - template.yaml

- name: Run Home Assistant container
  community.docker.docker_container:
    name: "{{ service.name }}"
    image: "{{ service.image }}:{{ service.version }}"
    state: started
    restart: true
    restart_policy: unless-stopped
    privileged: true
    network_mode: host
    # ports:
    #   - "{{ service.port }}:8123"
    # dns_servers:
    #   - 8.8.8.8
    #   - 1.1.1.1
    # networks:
    #   - name: "proxy"
    #   - name: "{{ smarthome.network }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # - /etc/resolv.conf:/etc/resolv.conf
      - /var/run/dbus:/var/run/dbus:ro
      # - /run/dbus:/run/dbus:ro
      - "{{ service.dir }}:/config"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ user.puid }}"
      PGID: "{{ user.pgid }}"
    capabilities:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
      - SYS_ADMIN
    devices:
      - "{{ smarthome.zigbee_adapter }}:{{ smarthome.zigbee_adapter }}"
      # Uncomment and adjust if Bluetooth device is present
      # - "/dev/ttyS0:/dev/ttyS0"
    labels:
      traefik.enable: "true"
      # traefik.docker.network: "{{ smarthome.network }}"
      traefik.http.routers.homeassistant.service: "{{ service.name }}"
      # # traefik.http.routers.homeassistant-local.rule: "Host(`192.168.0.180`) && PathPrefix(`/`)"
      traefik.http.routers.homeassistant.entrypoints: "web"
      # traefik.http.routers.homeassistant.service: "homeassistant"
      # traefik.http.routers.homeassistant.rule: "Host(`localhost`)"
      traefik.http.routers.homeassistant.rule: "Host(`{{ ansible_default_ipv4.address }}`)"
      # traefik.http.routers.homeassistant.rule: "PathPrefix(`/`)"
      # traefik.http.routers.homeassistant.rule: "Host(`{{ ansible_default_ipv4.address }}:{{ service.port }}`) && PathPrefix(`/`)"
      # traefik.http.routers.homeassistant.rule: "Host(`{{ ansible_default_ipv4.address }}`) && Port(`{{ service.port }}`)"
      # traefik.http.routers.homeassistant.rule: "Host(`{{ ansible_default_ipv4.address }}:{{ service.port }}`)"

      # traefik.http.routers.homeassistant-le.entrypoints: "websecure"
      # traefik.http.routers.homeassistant-le.service: "homeassistant"
      # traefik.http.routers.homeassistant-le.tls: "true"
      # traefik.http.routers.homeassistant-le.tls.certresolver: "letsencrypt"
      # traefik.http.routers.homeassistant-le.rule: "Host(`emwe.duckdns.org`)"

      traefik.http.services.homeassistant.loadbalancer.server.url: "http://127.0.0.1:{{ service.port }}"