- name: Create role directories
  file:
    path: "{{ homeassistant.dir }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'

- name: Deploy Home Assistant configuration file
  template:
    src: configuration.yaml.j2
    dest: "{{ homeassistant.dir }}/configuration.yaml"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"

- name: Ensure Home Assistant include folders exist
  file:
    path: "{{ homeassistant.dir }}/{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
  loop:
    # - automations
    - themes

- name: Ensure Home Assistant include files exist
  copy:
    dest: "{{ homeassistant.dir }}/{{ item }}"
    content: ""
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
    force: no
  loop:
    - automations.yaml
    - customize.yaml
    - groups.yaml
    - scripts.yaml
    - scenes.yaml
    - template.yaml

- name: "Ensure network exists ({{ homeassistant.network }})"
  when: homeassistant.network != "host"
  community.docker.docker_network:
    name: "{{ homeassistant.network }}"
    state: "present"

- name: Run Home Assistant container
  community.docker.docker_container:
    name: homeassistant
    image: lscr.io/linuxserver/homeassistant:latest
    state: started
    restart: true
    restart_policy: unless-stopped
    privileged: true
    network_mode: host
    # dns_servers:
    #   - 8.8.8.8
    #   - 1.1.1.1
    # networks:
    #   - name: "proxy"
    #   - name: "{{ homeassistant.network }}"
    volumes:
      - /var/run/dbus:/var/run/dbus:ro
      # - /etc/resolv.conf:/etc/resolv.conf
      # - /etc/localtime:/etc/localtime:ro
      - "{{ homeassistant.dir }}:/config"
    env:
      PUID: 1000
      PGID: 1000
      TZ: "{{ tz }}"
    capabilities:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
      - SYS_ADMIN
    devices:
      - "{{ smarthome.host_adapter }}:{{ smarthome.host_adapter }}"
      # Uncomment and adjust if Bluetooth device is present
      # - "/dev/ttyS0:/dev/ttyS0"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.homeassistant.entrypoints: "web"
      traefik.http.routers.homeassistant.service: "homeassistant"
      traefik.http.routers.homeassistant.rule: "Host(`192.168.0.180`) && PathPrefix(`/`)"
      traefik.http.services.homeassistant.loadbalancer.server.port: "{{ homeassistant.port }}"
