---
- name: "Create directories for: {{ service.name }}"
  file:
    path: "{{ service.dir }}"
    state: "directory"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"

- name: "Run Node-Red container"
  community.docker.docker_container:
    name: "{{ service.name }}"
    image: "{{ service.image }}:{{ service.version }}"
    state: "started"
    restart: true
    restart_policy: "unless-stopped"
    groups:
      - "dialout"
    networks:
      - name: "{{ smarthome.network }}"
    ports:
      - "{{ service.port }}:1880"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - "{{ service.dir }}:/data"
    env:
      TZ: "{{ tz }}"
      PUID: "1000"
      PGID: "1000"
    labels:
      traefik.enable: "true"
      # traefik.docker.network: "{{ smarthome.network }}"
      "{{ 'traefik.http.routers.' ~ service.name ~ '.entrypoints' }}": "websecure"
      "{{ 'traefik.http.routers.' ~ service.name ~ '.service' }}": "{{ service.name }}"
      "{{ 'traefik.http.routers.' ~ service.name ~ '.rule' }}": "Host(`{{ service.name }}.local`)"
      "{{ 'traefik.http.routers.' ~ service.name ~ '.tls' }}": "true"
      "{{ 'traefik.http.routers.' ~ service.name ~ '.tls.certresolver' }}": "letsencrypt"
      "{{ 'traefik.http.services.' ~ service.name ~ '.loadbalancer.server.port' }}": "{{ service.port }}"