name: Deploy to Kubernetes

on:
  push:
    paths:
      - 'k3s/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync Flux
        run: flux reconcile source git emhome